window.AETHER_FACTION_INDEX = [
  {
    "id": "9fxrb8_mq6pvvmm",
    "name": "Jyleth Fenon, Earth-Warden",
    "short": "Jyleth",
    "epithet": "Earth-Warden",
    "description": "Mineral-based organisms with geodic internal organs and extreme longevity.",
    "biology": "Lithoid",
    "race": "Lithoid",
    "seed": 570964868,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Lithoid alien species. composed of jagged rock and tectonic plates, crystalline geodic inclusions for eyes, mossy stony texture, mountain-like ruggedness, zero soft tissue. HEAD: Hammerhead structure with unique silhouette. EYES: 5 Pupil-less eyes that look completely non-human. SURFACE: Thick Warts texture with a #00f2ff primary hue. GARB: Wearing Tribal leather wraps. UNIQUE: Features Webbed Extremities. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Hammerhead",
    "eyeStyle": "Pupil-less",
    "eyeCount": 5,
    "clothing": "Tribal leather wraps",
    "markingPattern": "Thick Warts",
    "morphology": "Webbed Extremities",
    "color": "#00f2ff",
    "glyph": "✦",
    "primaryBiome": "Volcanic",
    "secondaryBiome": "Barren",
    "hostileBiome": "Water-World",
    "habitability": {
      "primary": "Volcanic",
      "secondary": "Barren",
      "hostile": "Water-World"
    },
    "disposition": {
      "aggression": 6,
      "devotion": 5,
      "expansionism": 3,
      "isolationism": 1,
      "mercantilism": 5
    },
    "aggression": 6,
    "devotion": 5,
    "expansionism": 3,
    "isolationism": 1,
    "mercantilism": 5,
    "civilisation": {
      "techBias": "Spiritual",
      "governmentType": "Warlord Council",
      "culture": "Faith"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20lithoid%20face%20portrait%2C%20thick%20warts%2C%20hammerhead%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=570964868",
    "portraitGitHubUrl": null,
    "portraitDriveUrl": null,
    "generatedAt": "2026-06-09T14:12:52.908Z",
    "botVersion": "1.0"
  },
  {
    "id": "2fd8z4_mq6pwozw",
    "name": "Oulkis Myndar, Energy-Burst",
    "short": "Oulkis",
    "epithet": "Energy-Burst",
    "description": "Vaporous energy-based beings that exist within magnetic containment fields.",
    "biology": "Ethereal",
    "race": "Ethereal",
    "seed": 146744752,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Ethereal alien species. body made of shifting nebulous gas and electrical arcs, held together by a magnetic harness, glowing semi-transparent forms, no solid skin. HEAD: Rectangular structure with unique silhouette. EYES: 6 Bioluminescent eyes that look completely non-human. SURFACE: Symmetrical Stripes texture with a #ff0055 primary hue. GARB: Wearing Holographic Shroud. UNIQUE: Features Writhing Tentacles. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Rectangular",
    "eyeStyle": "Bioluminescent",
    "eyeCount": 6,
    "clothing": "Holographic Shroud",
    "markingPattern": "Symmetrical Stripes",
    "morphology": "Writhing Tentacles",
    "color": "#ff0055",
    "glyph": "△",
    "primaryBiome": "Exotic",
    "secondaryBiome": "Barren",
    "hostileBiome": "Lush Forest",
    "habitability": {
      "primary": "Exotic",
      "secondary": "Barren",
      "hostile": "Lush Forest"
    },
    "disposition": {
      "aggression": 1,
      "devotion": 2,
      "expansionism": 1,
      "isolationism": 3,
      "mercantilism": 5
    },
    "aggression": 1,
    "devotion": 2,
    "expansionism": 1,
    "isolationism": 3,
    "mercantilism": 5,
    "civilisation": {
      "techBias": "Biological",
      "governmentType": "Warlord Council",
      "culture": "Faith"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20ethereal%20face%20portrait%2C%20symmetrical%20stripes%2C%20rectangular%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=146744752",
    "portraitGitHubUrl": null,
    "portraitDriveUrl": null,
    "generatedAt": "2026-06-09T14:12:52.908Z",
    "botVersion": "1.0"
  },
  {
    "id": "rsvmk7_mq6pxhk0",
    "name": "Myndar, The Obsidian",
    "short": "Myndar",
    "epithet": "The Obsidian",
    "description": "Mineral-based organisms with geodic internal organs and extreme longevity.",
    "biology": "Lithoid",
    "race": "Lithoid",
    "seed": 1681091575,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Lithoid alien species. composed of jagged rock and tectonic plates, crystalline geodic inclusions for eyes, mossy stony texture, mountain-like ruggedness, zero soft tissue. HEAD: Crustacean-like structure with unique silhouette. EYES: 8 Multiple-Small eyes that look completely non-human. SURFACE: Geodic Growths texture with a #9d00ff primary hue. GARB: Wearing Tribal leather wraps. UNIQUE: Features Multi-layered Crest. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Crustacean-like",
    "eyeStyle": "Multiple-Small",
    "eyeCount": 8,
    "clothing": "Tribal leather wraps",
    "markingPattern": "Geodic Growths",
    "morphology": "Multi-layered Crest",
    "color": "#9d00ff",
    "glyph": "◈",
    "primaryBiome": "Volcanic",
    "secondaryBiome": "Barren",
    "hostileBiome": "Water-World",
    "habitability": {
      "primary": "Volcanic",
      "secondary": "Barren",
      "hostile": "Water-World"
    },
    "disposition": {
      "aggression": 4,
      "devotion": 5,
      "expansionism": 5,
      "isolationism": 10,
      "mercantilism": 7
    },
    "aggression": 4,
    "devotion": 5,
    "expansionism": 5,
    "isolationism": 10,
    "mercantilism": 7,
    "civilisation": {
      "techBias": "Nomadic",
      "governmentType": "Warlord Council",
      "culture": "Dominance"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20lithoid%20face%20portrait%2C%20geodic%20growths%2C%20crustacean-like%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=1681091575",
    "portraitGitHubUrl": null,
    "portraitDriveUrl": null,
    "generatedAt": "2026-06-09T14:12:52.908Z",
    "botVersion": "1.0"
  },
  {
    "id": "1ijksvo_mq6pya3h",
    "name": "Xylius Vaxar, Coral-Guard",
    "short": "Xylius",
    "epithet": "Coral-Guard",
    "description": "Hydrodynamic lifeforms with pressure-resistant plating and sonar-based neural communication.",
    "biology": "Aquatic",
    "race": "Aquatic",
    "seed": 3298056756,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Aquatic alien species. thick rubbery skin like a whale or shark, translucent fins, wet glistening texture, deep-sea monstrous scales, absolutely NO human features. HEAD: Faceted structure with unique silhouette. EYES: 3 Cybernetic-monocle eyes that look completely non-human. SURFACE: Geometric Tattoos texture with a #00ff88 primary hue. GARB: Wearing Holographic Shroud. UNIQUE: Features Pressure-Resistant Fins. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Faceted",
    "eyeStyle": "Cybernetic-monocle",
    "eyeCount": 3,
    "clothing": "Holographic Shroud",
    "markingPattern": "Geometric Tattoos",
    "morphology": "Pressure-Resistant Fins",
    "color": "#00ff88",
    "glyph": "⬡",
    "primaryBiome": "Water-World",
    "secondaryBiome": "Sub-Surface Ocean Sphere",
    "hostileBiome": "Arid Desert",
    "habitability": {
      "primary": "Water-World",
      "secondary": "Sub-Surface Ocean Sphere",
      "hostile": "Arid Desert"
    },
    "disposition": {
      "aggression": 8,
      "devotion": 3,
      "expansionism": 7,
      "isolationism": 8,
      "mercantilism": 1
    },
    "aggression": 8,
    "devotion": 3,
    "expansionism": 7,
    "isolationism": 8,
    "mercantilism": 1,
    "civilisation": {
      "techBias": "Nomadic",
      "governmentType": "Democracy",
      "culture": "Freedom"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20aquatic%20face%20portrait%2C%20geometric%20tattoos%2C%20faceted%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=3298056756",
    "portraitGitHubUrl": null,
    "portraitDriveUrl": null,
    "generatedAt": "2026-06-09T14:12:52.908Z",
    "botVersion": "1.0"
  }
];