window.AETHER_FACTION_INDEX = [
  {
    "id": "1e6yfzf_mpallf5t",
    "name": "Oulok Zuleth, Abyssal-Ghost",
    "short": "Oulok",
    "epithet": "Abyssal-Ghost",
    "description": "Hydrodynamic lifeforms with pressure-resistant plating and sonar-based neural communication.",
    "biology": "Aquatic",
    "race": "Aquatic",
    "seed": 3034993515,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Aquatic alien species. thick rubbery skin like a whale or shark, translucent fins, wet glistening texture, deep-sea monstrous scales, absolutely NO human features. HEAD: Fin-Tipped structure with unique silhouette. EYES: 7 Milky-White eyes that look completely non-human. SURFACE: Mossy patches texture with a #00f2ff primary hue. GARB: Wearing Pragmatic Tech-Suit. UNIQUE: Features Writhing Tentacles. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Fin-Tipped",
    "eyeStyle": "Milky-White",
    "eyeCount": 7,
    "clothing": "Pragmatic Tech-Suit",
    "markingPattern": "Mossy patches",
    "morphology": "Writhing Tentacles",
    "color": "#00f2ff",
    "glyph": "✦",
    "primaryBiome": "Water-World",
    "secondaryBiome": "Sub-Surface Ocean Sphere",
    "hostileBiome": "Arid Desert",
    "habitability": {
      "primary": "Water-World",
      "secondary": "Sub-Surface Ocean Sphere",
      "hostile": "Arid Desert"
    },
    "disposition": {
      "aggression": 10,
      "devotion": 4,
      "expansionism": 7,
      "isolationism": 3,
      "mercantilism": 3
    },
    "aggression": 10,
    "devotion": 4,
    "expansionism": 7,
    "isolationism": 3,
    "mercantilism": 3,
    "civilisation": {
      "techBias": "Biological",
      "governmentType": "Democracy",
      "culture": "Survival"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20aquatic%20face%20portrait%2C%20mossy%20patches%2C%20fin-tipped%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=3034993515",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1e6yfzf_mpallf5t.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1e6yfzf_mpallf5t.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "pootx8_mpalm8f3",
    "name": "Vaxia Gryvox, The Mandible",
    "short": "Vaxia",
    "epithet": "The Mandible",
    "description": "Xenooids are chitinous organisms with complex social structures and highly efficient communal processing.",
    "biology": "Insectoid",
    "race": "Insectoid",
    "seed": 1553123708,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Insectoid alien species. hard chitinous exoskeleton, segmented thorax, chitin plating, bristly hairs, compound predatory insect features, no human nose or mouth. HEAD: Elephantine structure with unique silhouette. EYES: 3 Diamond eyes that look completely non-human. SURFACE: Star-Map Freckles texture with a #ff0055 primary hue. GARB: Wearing Scrap-Metal Armor. UNIQUE: Features Hollow Wing-Spans. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Elephantine",
    "eyeStyle": "Diamond",
    "eyeCount": 3,
    "clothing": "Scrap-Metal Armor",
    "markingPattern": "Star-Map Freckles",
    "morphology": "Hollow Wing-Spans",
    "color": "#ff0055",
    "glyph": "△",
    "primaryBiome": "Lush Forest",
    "secondaryBiome": "Volcanic",
    "hostileBiome": "Arctic Tundra",
    "habitability": {
      "primary": "Lush Forest",
      "secondary": "Volcanic",
      "hostile": "Arctic Tundra"
    },
    "disposition": {
      "aggression": 5,
      "devotion": 4,
      "expansionism": 4,
      "isolationism": 3,
      "mercantilism": 3
    },
    "aggression": 5,
    "devotion": 4,
    "expansionism": 4,
    "isolationism": 3,
    "mercantilism": 3,
    "civilisation": {
      "techBias": "Biological",
      "governmentType": "Warlord Council",
      "culture": "Survival"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20insectoid%20face%20portrait%2C%20star-map%20freckles%2C%20elephantine%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=1553123708",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_pootx8_mpalm8f3.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_pootx8_mpalm8f3.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "evjhrv_mpalnz9r",
    "name": "Bochon Xyl-an, The Hive-Speaker",
    "short": "Bochon",
    "epithet": "The Hive-Speaker",
    "description": "Xenooids are chitinous organisms with complex social structures and highly efficient communal processing.",
    "biology": "Insectoid",
    "race": "Insectoid",
    "seed": 899504059,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Insectoid alien species. hard chitinous exoskeleton, segmented thorax, chitin plating, bristly hairs, compound predatory insect features, no human nose or mouth. HEAD: Dome structure with unique silhouette. EYES: 3 Cybernetic-monocle eyes that look completely non-human. SURFACE: Leopard-like spots texture with a #9d00ff primary hue. GARB: Wearing Ceremonial Plate. UNIQUE: Features Ossified plates. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Dome",
    "eyeStyle": "Cybernetic-monocle",
    "eyeCount": 3,
    "clothing": "Ceremonial Plate",
    "markingPattern": "Leopard-like spots",
    "morphology": "Ossified plates",
    "color": "#9d00ff",
    "glyph": "◈",
    "primaryBiome": "Lush Forest",
    "secondaryBiome": "Volcanic",
    "hostileBiome": "Arctic Tundra",
    "habitability": {
      "primary": "Lush Forest",
      "secondary": "Volcanic",
      "hostile": "Arctic Tundra"
    },
    "disposition": {
      "aggression": 8,
      "devotion": 8,
      "expansionism": 8,
      "isolationism": 4,
      "mercantilism": 10
    },
    "aggression": 8,
    "devotion": 8,
    "expansionism": 8,
    "isolationism": 4,
    "mercantilism": 10,
    "civilisation": {
      "techBias": "Mechanical",
      "governmentType": "Theocracy",
      "culture": "Knowledge"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20insectoid%20face%20portrait%2C%20leopard-like%20spots%2C%20dome%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=899504059",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_evjhrv_mpalnz9r.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_evjhrv_mpalnz9r.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "5ryavq_mpalpqjg",
    "name": "Gorar, Sky-Watcher",
    "short": "Gorar",
    "epithet": "Sky-Watcher",
    "description": "Lightweight bipeds with hollow bone structures adapted for thin atmospheres.",
    "biology": "Avian",
    "race": "Avian",
    "seed": 349280918,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Avian alien species. covered in thick plumage or downy feathers, a hard keratin beak, hollow bone structure visible in neck, bird-like anatomy, predatory raptor features. HEAD: Crested structure with unique silhouette. EYES: 1 Clouded eyes that look completely non-human. SURFACE: Corroded Etchings texture with a #00ff88 primary hue. GARB: Wearing Tattered Nomad Cloak. UNIQUE: Features Extra sensory bristles. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Crested",
    "eyeStyle": "Clouded",
    "eyeCount": 1,
    "clothing": "Tattered Nomad Cloak",
    "markingPattern": "Corroded Etchings",
    "morphology": "Extra sensory bristles",
    "color": "#00ff88",
    "glyph": "⬡",
    "primaryBiome": "Exotic",
    "secondaryBiome": "Lush Forest",
    "hostileBiome": "Water-World",
    "habitability": {
      "primary": "Exotic",
      "secondary": "Lush Forest",
      "hostile": "Water-World"
    },
    "disposition": {
      "aggression": 1,
      "devotion": 4,
      "expansionism": 7,
      "isolationism": 2,
      "mercantilism": 10
    },
    "aggression": 1,
    "devotion": 4,
    "expansionism": 7,
    "isolationism": 2,
    "mercantilism": 10,
    "civilisation": {
      "techBias": "Mechanical",
      "governmentType": "Hive-mind",
      "culture": "Survival"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20avian%20face%20portrait%2C%20corroded%20etchings%2C%20crested%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=349280918",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_5ryavq_mpalpqjg.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_5ryavq_mpalpqjg.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "1kav4v7_mpalrhtg",
    "name": "Xylok Coalition, Shard-Mind",
    "short": "Xylok",
    "epithet": "Shard-Mind",
    "description": "Silicon-based lifeforms that process information through photonic resonance.",
    "biology": "Crystalline",
    "race": "Crystalline",
    "seed": 3404354659,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Crystalline alien species. jagged translucent quartz body, internal light refraction, sharp geometric planes, mineral-based life, reflecting light like a diamond. HEAD: Spherical structure with unique silhouette. EYES: 6 Clouded eyes that look completely non-human. SURFACE: Thick Warts texture with a #ff8800 primary hue. GARB: Wearing Phase-Shift Harness. UNIQUE: Features Writhing Tentacles. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Spherical",
    "eyeStyle": "Clouded",
    "eyeCount": 6,
    "clothing": "Phase-Shift Harness",
    "markingPattern": "Thick Warts",
    "morphology": "Writhing Tentacles",
    "color": "#ff8800",
    "glyph": "✴",
    "primaryBiome": "Barren",
    "secondaryBiome": "Arctic Tundra",
    "hostileBiome": "Water-World",
    "habitability": {
      "primary": "Barren",
      "secondary": "Arctic Tundra",
      "hostile": "Water-World"
    },
    "disposition": {
      "aggression": 1,
      "devotion": 6,
      "expansionism": 2,
      "isolationism": 1,
      "mercantilism": 3
    },
    "aggression": 1,
    "devotion": 6,
    "expansionism": 2,
    "isolationism": 1,
    "mercantilism": 3,
    "civilisation": {
      "techBias": "Spiritual",
      "governmentType": "Warlord Council",
      "culture": "Knowledge"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20crystalline%20face%20portrait%2C%20thick%20warts%2C%20spherical%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=3404354659",
    "portraitGitHubUrl": null,
    "portraitDriveUrl": null,
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "kxprpk_mpalu17m",
    "name": "Vaxar Dominion, Energy-Burst",
    "short": "Vaxar",
    "epithet": "Energy-Burst",
    "description": "Vaporous energy-based beings that exist within magnetic containment fields.",
    "biology": "Ethereal",
    "race": "Ethereal",
    "seed": 1265953160,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Ethereal alien species. body made of shifting nebulous gas and electrical arcs, held together by a magnetic harness, glowing semi-transparent forms, no solid skin. HEAD: Hammerhead structure with unique silhouette. EYES: 6 Pupil-less eyes that look completely non-human. SURFACE: Iridescent Scales texture with a #ffff00 primary hue. GARB: Wearing Scrap-Metal Armor. UNIQUE: Features Ossified plates. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Hammerhead",
    "eyeStyle": "Pupil-less",
    "eyeCount": 6,
    "clothing": "Scrap-Metal Armor",
    "markingPattern": "Iridescent Scales",
    "morphology": "Ossified plates",
    "color": "#ffff00",
    "glyph": "⊕",
    "primaryBiome": "Exotic",
    "secondaryBiome": "Barren",
    "hostileBiome": "Lush Forest",
    "habitability": {
      "primary": "Exotic",
      "secondary": "Barren",
      "hostile": "Lush Forest"
    },
    "disposition": {
      "aggression": 10,
      "devotion": 6,
      "expansionism": 7,
      "isolationism": 4,
      "mercantilism": 6
    },
    "aggression": 10,
    "devotion": 6,
    "expansionism": 7,
    "isolationism": 4,
    "mercantilism": 6,
    "civilisation": {
      "techBias": "Mechanical",
      "governmentType": "Merchant Guild",
      "culture": "Dominance"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20ethereal%20face%20portrait%2C%20iridescent%20scales%2C%20hammerhead%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=1265953160",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_kxprpk_mpalu17m.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_kxprpk_mpalu17m.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "cx9mbt_mpalvs52",
    "name": "Bochen Zular, Legacy-Bearer",
    "short": "Bochen",
    "epithet": "Legacy-Bearer",
    "description": "Endoskeletal bipeds with high neuro-plasticity and a propensity for rapid tool adaptation.",
    "biology": "Humanoid",
    "race": "Humanoid",
    "seed": 781470281,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Humanoid alien species. diverse non-human facial features, unusual proportions, exotic skin textures, unique ridge structures, avoid stereotypical grey alien look. HEAD: Fin-Tipped structure with unique silhouette. EYES: 4 Clouded eyes that look completely non-human. SURFACE: Geometric Tattoos texture with a #00f2ff primary hue. GARB: Wearing Bio-Organic Wrap. UNIQUE: Features Webbed Extremities. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Fin-Tipped",
    "eyeStyle": "Clouded",
    "eyeCount": 4,
    "clothing": "Bio-Organic Wrap",
    "markingPattern": "Geometric Tattoos",
    "morphology": "Webbed Extremities",
    "color": "#00f2ff",
    "glyph": "✦",
    "primaryBiome": "Lush Forest",
    "secondaryBiome": "Sub-Surface Ocean Sphere",
    "hostileBiome": "Barren",
    "habitability": {
      "primary": "Lush Forest",
      "secondary": "Sub-Surface Ocean Sphere",
      "hostile": "Barren"
    },
    "disposition": {
      "aggression": 9,
      "devotion": 5,
      "expansionism": 5,
      "isolationism": 9,
      "mercantilism": 1
    },
    "aggression": 9,
    "devotion": 5,
    "expansionism": 5,
    "isolationism": 9,
    "mercantilism": 1,
    "civilisation": {
      "techBias": "Nomadic",
      "governmentType": "Merchant Guild",
      "culture": "Knowledge"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20humanoid%20face%20portrait%2C%20geometric%20tattoos%2C%20fin-tipped%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=781470281",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_cx9mbt_mpalvs52.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_cx9mbt_mpalvs52.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "1ky9fgw_mpalxin2",
    "name": "Zyrtor Order, Crystal-Heart",
    "short": "Zyrtor",
    "epithet": "Crystal-Heart",
    "description": "Mineral-based organisms with geodic internal organs and extreme longevity.",
    "biology": "Lithoid",
    "race": "Lithoid",
    "seed": 3443652752,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Lithoid alien species. composed of jagged rock and tectonic plates, crystalline geodic inclusions for eyes, mossy stony texture, mountain-like ruggedness, zero soft tissue. HEAD: Featureless structure with unique silhouette. EYES: 6 Clouded eyes that look completely non-human. SURFACE: Flowing Circuitry texture with a #ff0055 primary hue. GARB: Wearing Pragmatic Tech-Suit. UNIQUE: Features Retractable Gills. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Featureless",
    "eyeStyle": "Clouded",
    "eyeCount": 6,
    "clothing": "Pragmatic Tech-Suit",
    "markingPattern": "Flowing Circuitry",
    "morphology": "Retractable Gills",
    "color": "#ff0055",
    "glyph": "△",
    "primaryBiome": "Volcanic",
    "secondaryBiome": "Barren",
    "hostileBiome": "Water-World",
    "habitability": {
      "primary": "Volcanic",
      "secondary": "Barren",
      "hostile": "Water-World"
    },
    "disposition": {
      "aggression": 5,
      "devotion": 5,
      "expansionism": 8,
      "isolationism": 8,
      "mercantilism": 1
    },
    "aggression": 5,
    "devotion": 5,
    "expansionism": 8,
    "isolationism": 8,
    "mercantilism": 1,
    "civilisation": {
      "techBias": "Spiritual",
      "governmentType": "Democracy",
      "culture": "Faith"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20lithoid%20face%20portrait%2C%20flowing%20circuitry%2C%20featureless%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=3443652752",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1ky9fgw_mpalxin2.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1ky9fgw_mpalxin2.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "m7lyq2_mpalz951",
    "name": "Zyr-an Jyltor, The Overclocked",
    "short": "Zyr-an",
    "epithet": "The Overclocked",
    "description": "Automated synthetics driven by crystalline logic cores and advanced energy cells.",
    "biology": "Mechanical",
    "race": "Mechanical",
    "seed": 1343037962,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Mechanical alien species. exposed wiring and hydraulic pistons, weathered industrial metal casing, worn plating, antique robotics, oil-stained machinery. HEAD: Flat structure with unique silhouette. EYES: 6 Compound eyes that look completely non-human. SURFACE: Thick Warts texture with a #9d00ff primary hue. GARB: Wearing Holographic Shroud. UNIQUE: Features Metallic Spikes. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Flat",
    "eyeStyle": "Compound",
    "eyeCount": 6,
    "clothing": "Holographic Shroud",
    "markingPattern": "Thick Warts",
    "morphology": "Metallic Spikes",
    "color": "#9d00ff",
    "glyph": "◈",
    "primaryBiome": "Barren",
    "secondaryBiome": "Volcanic",
    "hostileBiome": "Water-World",
    "habitability": {
      "primary": "Barren",
      "secondary": "Volcanic",
      "hostile": "Water-World"
    },
    "disposition": {
      "aggression": 3,
      "devotion": 2,
      "expansionism": 5,
      "isolationism": 5,
      "mercantilism": 10
    },
    "aggression": 3,
    "devotion": 2,
    "expansionism": 5,
    "isolationism": 5,
    "mercantilism": 10,
    "civilisation": {
      "techBias": "Nomadic",
      "governmentType": "Hive-mind",
      "culture": "Survival"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20mechanical%20face%20portrait%2C%20thick%20warts%2C%20flat%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=1343037962",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_m7lyq2_mpalz951.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_m7lyq2_mpalz951.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "a6x3xk_mpam1jpf",
    "name": "Zyren Zulon, The Luminous",
    "short": "Zyren",
    "epithet": "The Luminous",
    "description": "Vaporous energy-based beings that exist within magnetic containment fields.",
    "biology": "Ethereal",
    "race": "Ethereal",
    "seed": 616284200,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Ethereal alien species. body made of shifting nebulous gas and electrical arcs, held together by a magnetic harness, glowing semi-transparent forms, no solid skin. HEAD: Hooded structure with unique silhouette. EYES: 3 Holographic eyes that look completely non-human. SURFACE: Runic Carvings texture with a #00ff88 primary hue. GARB: Wearing Tribal leather wraps. UNIQUE: Features Retractable Gills. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Hooded",
    "eyeStyle": "Holographic",
    "eyeCount": 3,
    "clothing": "Tribal leather wraps",
    "markingPattern": "Runic Carvings",
    "morphology": "Retractable Gills",
    "color": "#00ff88",
    "glyph": "⬡",
    "primaryBiome": "Exotic",
    "secondaryBiome": "Barren",
    "hostileBiome": "Lush Forest",
    "habitability": {
      "primary": "Exotic",
      "secondary": "Barren",
      "hostile": "Lush Forest"
    },
    "disposition": {
      "aggression": 7,
      "devotion": 7,
      "expansionism": 8,
      "isolationism": 1,
      "mercantilism": 8
    },
    "aggression": 7,
    "devotion": 7,
    "expansionism": 8,
    "isolationism": 1,
    "mercantilism": 8,
    "civilisation": {
      "techBias": "Mechanical",
      "governmentType": "Warlord Council",
      "culture": "Freedom"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20ethereal%20face%20portrait%2C%20runic%20carvings%2C%20hooded%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=616284200",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_a6x3xk_mpam1jpf.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_a6x3xk_mpam1jpf.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "12f862m_mpam3ls3",
    "name": "Vaxia Pylok, Static-Gazer",
    "short": "Vaxia",
    "epithet": "Static-Gazer",
    "description": "Silicon-based lifeforms that process information through photonic resonance.",
    "biology": "Crystalline",
    "race": "Crystalline",
    "seed": 2323290046,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Crystalline alien species. jagged translucent quartz body, internal light refraction, sharp geometric planes, mineral-based life, reflecting light like a diamond. HEAD: Spherical structure with unique silhouette. EYES: 4 Milky-White eyes that look completely non-human. SURFACE: Thick Warts texture with a #ff8800 primary hue. GARB: Wearing Minimalist Tunic. UNIQUE: Features Large Curved Horns. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Spherical",
    "eyeStyle": "Milky-White",
    "eyeCount": 4,
    "clothing": "Minimalist Tunic",
    "markingPattern": "Thick Warts",
    "morphology": "Large Curved Horns",
    "color": "#ff8800",
    "glyph": "✴",
    "primaryBiome": "Barren",
    "secondaryBiome": "Arctic Tundra",
    "hostileBiome": "Water-World",
    "habitability": {
      "primary": "Barren",
      "secondary": "Arctic Tundra",
      "hostile": "Water-World"
    },
    "disposition": {
      "aggression": 2,
      "devotion": 6,
      "expansionism": 3,
      "isolationism": 4,
      "mercantilism": 8
    },
    "aggression": 2,
    "devotion": 6,
    "expansionism": 3,
    "isolationism": 4,
    "mercantilism": 8,
    "civilisation": {
      "techBias": "Spiritual",
      "governmentType": "Democracy",
      "culture": "Faith"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20crystalline%20face%20portrait%2C%20thick%20warts%2C%20spherical%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=2323290046",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_12f862m_mpam3ls3.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_12f862m_mpam3ls3.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "gjxmqf_mpam5d1v",
    "name": "Bocheth Vaken, Talon-Lord",
    "short": "Bocheth",
    "epithet": "Talon-Lord",
    "description": "Lightweight bipeds with hollow bone structures adapted for thin atmospheres.",
    "biology": "Avian",
    "race": "Avian",
    "seed": 1000940631,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Avian alien species. covered in thick plumage or downy feathers, a hard keratin beak, hollow bone structure visible in neck, bird-like anatomy, predatory raptor features. HEAD: Dome structure with unique silhouette. EYES: 2 Pupil-less eyes that look completely non-human. SURFACE: Geometric Tattoos texture with a #ffff00 primary hue. GARB: Wearing Tribal leather wraps. UNIQUE: Features Bioluminescent Halos. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Dome",
    "eyeStyle": "Pupil-less",
    "eyeCount": 2,
    "clothing": "Tribal leather wraps",
    "markingPattern": "Geometric Tattoos",
    "morphology": "Bioluminescent Halos",
    "color": "#ffff00",
    "glyph": "⊕",
    "primaryBiome": "Exotic",
    "secondaryBiome": "Lush Forest",
    "hostileBiome": "Water-World",
    "habitability": {
      "primary": "Exotic",
      "secondary": "Lush Forest",
      "hostile": "Water-World"
    },
    "disposition": {
      "aggression": 9,
      "devotion": 5,
      "expansionism": 3,
      "isolationism": 9,
      "mercantilism": 10
    },
    "aggression": 9,
    "devotion": 5,
    "expansionism": 3,
    "isolationism": 9,
    "mercantilism": 10,
    "civilisation": {
      "techBias": "Mechanical",
      "governmentType": "Hive-mind",
      "culture": "Survival"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20avian%20face%20portrait%2C%20geometric%20tattoos%2C%20dome%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=1000940631",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_gjxmqf_mpam5d1v.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_gjxmqf_mpam5d1v.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "3me2le_mpam74bk",
    "name": "Xyleth Ascendancy, The Eternal",
    "short": "Xyleth",
    "epithet": "The Eternal",
    "description": "Vaporous energy-based beings that exist within magnetic containment fields.",
    "biology": "Ethereal",
    "race": "Ethereal",
    "seed": 219006626,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Ethereal alien species. body made of shifting nebulous gas and electrical arcs, held together by a magnetic harness, glowing semi-transparent forms, no solid skin. HEAD: Snouted structure with unique silhouette. EYES: 6 Compound eyes that look completely non-human. SURFACE: Iridescent Scales texture with a #00f2ff primary hue. GARB: Wearing Bio-Organic Wrap. UNIQUE: Features Multi-layered Crest. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Snouted",
    "eyeStyle": "Compound",
    "eyeCount": 6,
    "clothing": "Bio-Organic Wrap",
    "markingPattern": "Iridescent Scales",
    "morphology": "Multi-layered Crest",
    "color": "#00f2ff",
    "glyph": "✦",
    "primaryBiome": "Exotic",
    "secondaryBiome": "Barren",
    "hostileBiome": "Lush Forest",
    "habitability": {
      "primary": "Exotic",
      "secondary": "Barren",
      "hostile": "Lush Forest"
    },
    "disposition": {
      "aggression": 4,
      "devotion": 9,
      "expansionism": 8,
      "isolationism": 4,
      "mercantilism": 7
    },
    "aggression": 4,
    "devotion": 9,
    "expansionism": 8,
    "isolationism": 4,
    "mercantilism": 7,
    "civilisation": {
      "techBias": "Mechanical",
      "governmentType": "Theocracy",
      "culture": "Dominance"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20ethereal%20face%20portrait%2C%20iridescent%20scales%2C%20snouted%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=219006626",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_3me2le_mpam74bk.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_3me2le_mpam74bk.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "eg8ueb_mpam8vlb",
    "name": "Vaxia, The Current-Walker",
    "short": "Vaxia",
    "epithet": "The Current-Walker",
    "description": "Hydrodynamic lifeforms with pressure-resistant plating and sonar-based neural communication.",
    "biology": "Aquatic",
    "race": "Aquatic",
    "seed": 873812963,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Aquatic alien species. thick rubbery skin like a whale or shark, translucent fins, wet glistening texture, deep-sea monstrous scales, absolutely NO human features. HEAD: Elongated structure with unique silhouette. EYES: 5 Holographic eyes that look completely non-human. SURFACE: Corroded Etchings texture with a #ff0055 primary hue. GARB: Wearing Minimalist Tunic. UNIQUE: Features Prehensile trunks. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Elongated",
    "eyeStyle": "Holographic",
    "eyeCount": 5,
    "clothing": "Minimalist Tunic",
    "markingPattern": "Corroded Etchings",
    "morphology": "Prehensile trunks",
    "color": "#ff0055",
    "glyph": "△",
    "primaryBiome": "Water-World",
    "secondaryBiome": "Sub-Surface Ocean Sphere",
    "hostileBiome": "Arid Desert",
    "habitability": {
      "primary": "Water-World",
      "secondary": "Sub-Surface Ocean Sphere",
      "hostile": "Arid Desert"
    },
    "disposition": {
      "aggression": 6,
      "devotion": 9,
      "expansionism": 2,
      "isolationism": 8,
      "mercantilism": 6
    },
    "aggression": 6,
    "devotion": 9,
    "expansionism": 2,
    "isolationism": 8,
    "mercantilism": 6,
    "civilisation": {
      "techBias": "Mechanical",
      "governmentType": "Democracy",
      "culture": "Freedom"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20aquatic%20face%20portrait%2C%20corroded%20etchings%2C%20elongated%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=873812963",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_eg8ueb_mpam8vlb.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_eg8ueb_mpam8vlb.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "1xeom3x_mpambhqf",
    "name": "Zyron Kraok, Void-Shadow",
    "short": "Zyron",
    "epithet": "Void-Shadow",
    "description": "Vaporous energy-based beings that exist within magnetic containment fields.",
    "biology": "Ethereal",
    "race": "Ethereal",
    "seed": 4196829165,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Ethereal alien species. body made of shifting nebulous gas and electrical arcs, held together by a magnetic harness, glowing semi-transparent forms, no solid skin. HEAD: Spherical structure with unique silhouette. EYES: 2 Multiple-Small eyes that look completely non-human. SURFACE: Geodic Growths texture with a #9d00ff primary hue. GARB: Wearing Phase-Shift Harness. UNIQUE: Features Multiple chins. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Spherical",
    "eyeStyle": "Multiple-Small",
    "eyeCount": 2,
    "clothing": "Phase-Shift Harness",
    "markingPattern": "Geodic Growths",
    "morphology": "Multiple chins",
    "color": "#9d00ff",
    "glyph": "◈",
    "primaryBiome": "Exotic",
    "secondaryBiome": "Barren",
    "hostileBiome": "Lush Forest",
    "habitability": {
      "primary": "Exotic",
      "secondary": "Barren",
      "hostile": "Lush Forest"
    },
    "disposition": {
      "aggression": 5,
      "devotion": 6,
      "expansionism": 4,
      "isolationism": 1,
      "mercantilism": 6
    },
    "aggression": 5,
    "devotion": 6,
    "expansionism": 4,
    "isolationism": 1,
    "mercantilism": 6,
    "civilisation": {
      "techBias": "Spiritual",
      "governmentType": "Warlord Council",
      "culture": "Freedom"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20ethereal%20face%20portrait%2C%20geodic%20growths%2C%20spherical%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=4196829165",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1xeom3x_mpambhqf.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1xeom3x_mpambhqf.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "1ihknov_mpamd907",
    "name": "Zyrtor, Static-Gazer",
    "short": "Zyrtor",
    "epithet": "Static-Gazer",
    "description": "Silicon-based lifeforms that process information through photonic resonance.",
    "biology": "Crystalline",
    "race": "Crystalline",
    "seed": 3294690799,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Crystalline alien species. jagged translucent quartz body, internal light refraction, sharp geometric planes, mineral-based life, reflecting light like a diamond. HEAD: Tubular structure with unique silhouette. EYES: 1 Cybernetic-monocle eyes that look completely non-human. SURFACE: Tiger-like banding texture with a #00ff88 primary hue. GARB: Wearing Scrap-Metal Armor. UNIQUE: Features Prehensile trunks. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Tubular",
    "eyeStyle": "Cybernetic-monocle",
    "eyeCount": 1,
    "clothing": "Scrap-Metal Armor",
    "markingPattern": "Tiger-like banding",
    "morphology": "Prehensile trunks",
    "color": "#00ff88",
    "glyph": "⬡",
    "primaryBiome": "Barren",
    "secondaryBiome": "Arctic Tundra",
    "hostileBiome": "Water-World",
    "habitability": {
      "primary": "Barren",
      "secondary": "Arctic Tundra",
      "hostile": "Water-World"
    },
    "disposition": {
      "aggression": 2,
      "devotion": 7,
      "expansionism": 3,
      "isolationism": 9,
      "mercantilism": 3
    },
    "aggression": 2,
    "devotion": 7,
    "expansionism": 3,
    "isolationism": 9,
    "mercantilism": 3,
    "civilisation": {
      "techBias": "Biological",
      "governmentType": "Warlord Council",
      "culture": "Dominance"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20crystalline%20face%20portrait%2C%20tiger-like%20banding%2C%20tubular%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=3294690799",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1ihknov_mpamd907.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1ihknov_mpamd907.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "1j9q37y_mpamf0a7",
    "name": "Vaxix, The Hydrophile",
    "short": "Vaxix",
    "epithet": "The Hydrophile",
    "description": "Hydrodynamic lifeforms with pressure-resistant plating and sonar-based neural communication.",
    "biology": "Aquatic",
    "race": "Aquatic",
    "seed": 3341973454,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Aquatic alien species. thick rubbery skin like a whale or shark, translucent fins, wet glistening texture, deep-sea monstrous scales, absolutely NO human features. HEAD: Spherical structure with unique silhouette. EYES: 1 Slit eyes that look completely non-human. SURFACE: Iridescent Scales texture with a #ff8800 primary hue. GARB: Wearing Ancient monk robes. UNIQUE: Features Metallic Spikes. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Spherical",
    "eyeStyle": "Slit",
    "eyeCount": 1,
    "clothing": "Ancient monk robes",
    "markingPattern": "Iridescent Scales",
    "morphology": "Metallic Spikes",
    "color": "#ff8800",
    "glyph": "✴",
    "primaryBiome": "Water-World",
    "secondaryBiome": "Sub-Surface Ocean Sphere",
    "hostileBiome": "Arid Desert",
    "habitability": {
      "primary": "Water-World",
      "secondary": "Sub-Surface Ocean Sphere",
      "hostile": "Arid Desert"
    },
    "disposition": {
      "aggression": 9,
      "devotion": 2,
      "expansionism": 2,
      "isolationism": 3,
      "mercantilism": 4
    },
    "aggression": 9,
    "devotion": 2,
    "expansionism": 2,
    "isolationism": 3,
    "mercantilism": 4,
    "civilisation": {
      "techBias": "Biological",
      "governmentType": "Theocracy",
      "culture": "Dominance"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20aquatic%20face%20portrait%2C%20iridescent%20scales%2C%20spherical%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=3341973454",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1j9q37y_mpamf0a7.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1j9q37y_mpamf0a7.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "7t16p4_mpamgrjy",
    "name": "Myn-an, Bio-Mass",
    "short": "Myn-an",
    "epithet": "Bio-Mass",
    "description": "Highly adaptive protoplasmic entities capable of rapid cellular reconfiguration.",
    "biology": "Amorphous",
    "race": "Amorphous",
    "seed": 472027432,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Amorphous alien species. viscous translucent slime, shifting protoplasmic mass, lack of symmetry, gelatinous undulating surface, multiple small erratic nuclei. HEAD: Crustacean-like structure with unique silhouette. EYES: 8 Holographic eyes that look completely non-human. SURFACE: Flowing Circuitry texture with a #ffff00 primary hue. GARB: Wearing Pilot's flight jacket. UNIQUE: Features Pressure-Resistant Fins. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Crustacean-like",
    "eyeStyle": "Holographic",
    "eyeCount": 8,
    "clothing": "Pilot's flight jacket",
    "markingPattern": "Flowing Circuitry",
    "morphology": "Pressure-Resistant Fins",
    "color": "#ffff00",
    "glyph": "⊕",
    "primaryBiome": "Sub-Surface Ocean Sphere",
    "secondaryBiome": "Water-World",
    "hostileBiome": "Barren",
    "habitability": {
      "primary": "Sub-Surface Ocean Sphere",
      "secondary": "Water-World",
      "hostile": "Barren"
    },
    "disposition": {
      "aggression": 10,
      "devotion": 10,
      "expansionism": 3,
      "isolationism": 3,
      "mercantilism": 7
    },
    "aggression": 10,
    "devotion": 10,
    "expansionism": 3,
    "isolationism": 3,
    "mercantilism": 7,
    "civilisation": {
      "techBias": "Biological",
      "governmentType": "Merchant Guild",
      "culture": "Knowledge"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20amorphous%20face%20portrait%2C%20flowing%20circuitry%2C%20crustacean-like%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=472027432",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_7t16p4_mpamgrjy.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_7t16p4_mpamgrjy.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "b4302i_mpamiitn",
    "name": "Zyrdar Vaxen, Coral-Guard",
    "short": "Zyrdar",
    "epithet": "Coral-Guard",
    "description": "Hydrodynamic lifeforms with pressure-resistant plating and sonar-based neural communication.",
    "biology": "Aquatic",
    "race": "Aquatic",
    "seed": 671986458,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Aquatic alien species. thick rubbery skin like a whale or shark, translucent fins, wet glistening texture, deep-sea monstrous scales, absolutely NO human features. HEAD: Crustacean-like structure with unique silhouette. EYES: 5 Compound eyes that look completely non-human. SURFACE: Mossy patches texture with a #00f2ff primary hue. GARB: Wearing Bio-Organic Wrap. UNIQUE: Features Writhing Tentacles. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Crustacean-like",
    "eyeStyle": "Compound",
    "eyeCount": 5,
    "clothing": "Bio-Organic Wrap",
    "markingPattern": "Mossy patches",
    "morphology": "Writhing Tentacles",
    "color": "#00f2ff",
    "glyph": "✦",
    "primaryBiome": "Water-World",
    "secondaryBiome": "Sub-Surface Ocean Sphere",
    "hostileBiome": "Arid Desert",
    "habitability": {
      "primary": "Water-World",
      "secondary": "Sub-Surface Ocean Sphere",
      "hostile": "Arid Desert"
    },
    "disposition": {
      "aggression": 6,
      "devotion": 7,
      "expansionism": 2,
      "isolationism": 5,
      "mercantilism": 1
    },
    "aggression": 6,
    "devotion": 7,
    "expansionism": 2,
    "isolationism": 5,
    "mercantilism": 1,
    "civilisation": {
      "techBias": "Biological",
      "governmentType": "Theocracy",
      "culture": "Faith"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20aquatic%20face%20portrait%2C%20mossy%20patches%2C%20crustacean-like%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=671986458",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_b4302i_mpamiitn.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_b4302i_mpamiitn.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "11a3gh7_mpaml4ys",
    "name": "Ouldar Ascendancy, Swarmer",
    "short": "Ouldar",
    "epithet": "Swarmer",
    "description": "Xenooids are chitinous organisms with complex social structures and highly efficient communal processing.",
    "biology": "Insectoid",
    "race": "Insectoid",
    "seed": 2254205995,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Insectoid alien species. hard chitinous exoskeleton, segmented thorax, chitin plating, bristly hairs, compound predatory insect features, no human nose or mouth. HEAD: Angular structure with unique silhouette. EYES: 7 Glowing-dots eyes that look completely non-human. SURFACE: Iridescent Scales texture with a #ff0055 primary hue. GARB: Wearing Pressure Suit. UNIQUE: Features Multiple chins. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Angular",
    "eyeStyle": "Glowing-dots",
    "eyeCount": 7,
    "clothing": "Pressure Suit",
    "markingPattern": "Iridescent Scales",
    "morphology": "Multiple chins",
    "color": "#ff0055",
    "glyph": "△",
    "primaryBiome": "Lush Forest",
    "secondaryBiome": "Volcanic",
    "hostileBiome": "Arctic Tundra",
    "habitability": {
      "primary": "Lush Forest",
      "secondary": "Volcanic",
      "hostile": "Arctic Tundra"
    },
    "disposition": {
      "aggression": 10,
      "devotion": 2,
      "expansionism": 3,
      "isolationism": 1,
      "mercantilism": 9
    },
    "aggression": 10,
    "devotion": 2,
    "expansionism": 3,
    "isolationism": 1,
    "mercantilism": 9,
    "civilisation": {
      "techBias": "Biological",
      "governmentType": "Theocracy",
      "culture": "Freedom"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20insectoid%20face%20portrait%2C%20iridescent%20scales%2C%20angular%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=2254205995",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_11a3gh7_mpaml4ys.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_11a3gh7_mpaml4ys.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "1gqu1lo_mpammx01",
    "name": "Ter-an Vakus, The Adaptable",
    "short": "Ter-an",
    "epithet": "The Adaptable",
    "description": "Endoskeletal bipeds with high neuro-plasticity and a propensity for rapid tool adaptation.",
    "biology": "Humanoid",
    "race": "Humanoid",
    "seed": 3189312924,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Humanoid alien species. diverse non-human facial features, unusual proportions, exotic skin textures, unique ridge structures, avoid stereotypical grey alien look. HEAD: Angular structure with unique silhouette. EYES: 8 Milky-White eyes that look completely non-human. SURFACE: Iridescent Scales texture with a #9d00ff primary hue. GARB: Wearing Tattered Nomad Cloak. UNIQUE: Features Prehensile trunks. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Angular",
    "eyeStyle": "Milky-White",
    "eyeCount": 8,
    "clothing": "Tattered Nomad Cloak",
    "markingPattern": "Iridescent Scales",
    "morphology": "Prehensile trunks",
    "color": "#9d00ff",
    "glyph": "◈",
    "primaryBiome": "Lush Forest",
    "secondaryBiome": "Sub-Surface Ocean Sphere",
    "hostileBiome": "Barren",
    "habitability": {
      "primary": "Lush Forest",
      "secondary": "Sub-Surface Ocean Sphere",
      "hostile": "Barren"
    },
    "disposition": {
      "aggression": 5,
      "devotion": 7,
      "expansionism": 7,
      "isolationism": 9,
      "mercantilism": 10
    },
    "aggression": 5,
    "devotion": 7,
    "expansionism": 7,
    "isolationism": 9,
    "mercantilism": 10,
    "civilisation": {
      "techBias": "Biological",
      "governmentType": "Theocracy",
      "culture": "Knowledge"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20humanoid%20face%20portrait%2C%20iridescent%20scales%2C%20angular%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=3189312924",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1gqu1lo_mpammx01.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1gqu1lo_mpammx01.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "1t7jgt6_mpamooa2",
    "name": "Mynkis, Deep-Diver",
    "short": "Mynkis",
    "epithet": "Deep-Diver",
    "description": "Hydrodynamic lifeforms with pressure-resistant plating and sonar-based neural communication.",
    "biology": "Aquatic",
    "race": "Aquatic",
    "seed": 3942967002,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Aquatic alien species. thick rubbery skin like a whale or shark, translucent fins, wet glistening texture, deep-sea monstrous scales, absolutely NO human features. HEAD: Hooded structure with unique silhouette. EYES: 8 Single-Large eyes that look completely non-human. SURFACE: Asymmetrical Splatter texture with a #00ff88 primary hue. GARB: Wearing Ceremonial Plate. UNIQUE: Features Extra sensory bristles. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Hooded",
    "eyeStyle": "Single-Large",
    "eyeCount": 8,
    "clothing": "Ceremonial Plate",
    "markingPattern": "Asymmetrical Splatter",
    "morphology": "Extra sensory bristles",
    "color": "#00ff88",
    "glyph": "⬡",
    "primaryBiome": "Water-World",
    "secondaryBiome": "Sub-Surface Ocean Sphere",
    "hostileBiome": "Arid Desert",
    "habitability": {
      "primary": "Water-World",
      "secondary": "Sub-Surface Ocean Sphere",
      "hostile": "Arid Desert"
    },
    "disposition": {
      "aggression": 2,
      "devotion": 10,
      "expansionism": 1,
      "isolationism": 7,
      "mercantilism": 5
    },
    "aggression": 2,
    "devotion": 10,
    "expansionism": 1,
    "isolationism": 7,
    "mercantilism": 5,
    "civilisation": {
      "techBias": "Nomadic",
      "governmentType": "Merchant Guild",
      "culture": "Faith"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20aquatic%20face%20portrait%2C%20asymmetrical%20splatter%2C%20hooded%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=3942967002",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1t7jgt6_mpamooa2.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1t7jgt6_mpamooa2.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "4hzzsx_mpamqfjx",
    "name": "Xyldar, Shift-Walker",
    "short": "Xyldar",
    "epithet": "Shift-Walker",
    "description": "Vaporous energy-based beings that exist within magnetic containment fields.",
    "biology": "Ethereal",
    "race": "Ethereal",
    "seed": 272097537,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Ethereal alien species. body made of shifting nebulous gas and electrical arcs, held together by a magnetic harness, glowing semi-transparent forms, no solid skin. HEAD: Faceted structure with unique silhouette. EYES: 8 Diamond eyes that look completely non-human. SURFACE: Bioluminescent Veins texture with a #ff8800 primary hue. GARB: Wearing Pragmatic Tech-Suit. UNIQUE: Features Webbed Extremities. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Faceted",
    "eyeStyle": "Diamond",
    "eyeCount": 8,
    "clothing": "Pragmatic Tech-Suit",
    "markingPattern": "Bioluminescent Veins",
    "morphology": "Webbed Extremities",
    "color": "#ff8800",
    "glyph": "✴",
    "primaryBiome": "Exotic",
    "secondaryBiome": "Barren",
    "hostileBiome": "Lush Forest",
    "habitability": {
      "primary": "Exotic",
      "secondary": "Barren",
      "hostile": "Lush Forest"
    },
    "disposition": {
      "aggression": 7,
      "devotion": 9,
      "expansionism": 1,
      "isolationism": 3,
      "mercantilism": 8
    },
    "aggression": 7,
    "devotion": 9,
    "expansionism": 1,
    "isolationism": 3,
    "mercantilism": 8,
    "civilisation": {
      "techBias": "Mechanical",
      "governmentType": "Merchant Guild",
      "culture": "Dominance"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20ethereal%20face%20portrait%2C%20bioluminescent%20veins%2C%20faceted%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=272097537",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_4hzzsx_mpamqfjx.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_4hzzsx_mpamqfjx.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "qjvy55_mpams6tl",
    "name": "Zyrar, Venom-Tongue",
    "short": "Zyrar",
    "epithet": "Venom-Tongue",
    "description": "Cold-blooded saurians with reinforced dermal plating and acute predatory instincts.",
    "biology": "Reptilian",
    "race": "Reptilian",
    "seed": 1605523865,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Reptilian alien species. thick crocodilian scales, leathery skin, heavy brow ridges, cold-blooded predatory gaze, dinosaur-like textures. HEAD: Hooded structure with unique silhouette. EYES: 2 Slit eyes that look completely non-human. SURFACE: Bioluminescent Veins texture with a #ffff00 primary hue. GARB: Wearing Ancient monk robes. UNIQUE: Features Webbed Extremities. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Hooded",
    "eyeStyle": "Slit",
    "eyeCount": 2,
    "clothing": "Ancient monk robes",
    "markingPattern": "Bioluminescent Veins",
    "morphology": "Webbed Extremities",
    "color": "#ffff00",
    "glyph": "⊕",
    "primaryBiome": "Arid Desert",
    "secondaryBiome": "Volcanic",
    "hostileBiome": "Arctic Tundra",
    "habitability": {
      "primary": "Arid Desert",
      "secondary": "Volcanic",
      "hostile": "Arctic Tundra"
    },
    "disposition": {
      "aggression": 5,
      "devotion": 7,
      "expansionism": 8,
      "isolationism": 6,
      "mercantilism": 2
    },
    "aggression": 5,
    "devotion": 7,
    "expansionism": 8,
    "isolationism": 6,
    "mercantilism": 2,
    "civilisation": {
      "techBias": "Mechanical",
      "governmentType": "Democracy",
      "culture": "Faith"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20reptilian%20face%20portrait%2C%20bioluminescent%20veins%2C%20hooded%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=1605523865",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_qjvy55_mpams6tl.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_qjvy55_mpams6tl.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "12wlktg_mpamusyn",
    "name": "Vaxeth, Prism-Guard",
    "short": "Vaxeth",
    "epithet": "Prism-Guard",
    "description": "Silicon-based lifeforms that process information through photonic resonance.",
    "biology": "Crystalline",
    "race": "Crystalline",
    "seed": 2352469156,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Crystalline alien species. jagged translucent quartz body, internal light refraction, sharp geometric planes, mineral-based life, reflecting light like a diamond. HEAD: Hooded structure with unique silhouette. EYES: 5 Milky-White eyes that look completely non-human. SURFACE: Runic Carvings texture with a #00f2ff primary hue. GARB: Wearing Heavy Industrial Gear. UNIQUE: Features Multi-layered Crest. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Hooded",
    "eyeStyle": "Milky-White",
    "eyeCount": 5,
    "clothing": "Heavy Industrial Gear",
    "markingPattern": "Runic Carvings",
    "morphology": "Multi-layered Crest",
    "color": "#00f2ff",
    "glyph": "✦",
    "primaryBiome": "Barren",
    "secondaryBiome": "Arctic Tundra",
    "hostileBiome": "Water-World",
    "habitability": {
      "primary": "Barren",
      "secondary": "Arctic Tundra",
      "hostile": "Water-World"
    },
    "disposition": {
      "aggression": 7,
      "devotion": 7,
      "expansionism": 6,
      "isolationism": 3,
      "mercantilism": 4
    },
    "aggression": 7,
    "devotion": 7,
    "expansionism": 6,
    "isolationism": 3,
    "mercantilism": 4,
    "civilisation": {
      "techBias": "Nomadic",
      "governmentType": "Warlord Council",
      "culture": "Freedom"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20crystalline%20face%20portrait%2C%20runic%20carvings%2C%20hooded%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=2352469156",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_12wlktg_mpamusyn.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_12wlktg_mpamusyn.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "2a9jyf_mpamwjgp",
    "name": "Terok Ascendancy, Gear-Warden",
    "short": "Terok",
    "epithet": "Gear-Warden",
    "description": "Automated synthetics driven by crystalline logic cores and advanced energy cells.",
    "biology": "Mechanical",
    "race": "Mechanical",
    "seed": 138174279,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Mechanical alien species. exposed wiring and hydraulic pistons, weathered industrial metal casing, worn plating, antique robotics, oil-stained machinery. HEAD: Flat structure with unique silhouette. EYES: 3 Single-Large eyes that look completely non-human. SURFACE: Iridescent Scales texture with a #ff0055 primary hue. GARB: Wearing Pragmatic Tech-Suit. UNIQUE: Features Multiple chins. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Flat",
    "eyeStyle": "Single-Large",
    "eyeCount": 3,
    "clothing": "Pragmatic Tech-Suit",
    "markingPattern": "Iridescent Scales",
    "morphology": "Multiple chins",
    "color": "#ff0055",
    "glyph": "△",
    "primaryBiome": "Barren",
    "secondaryBiome": "Volcanic",
    "hostileBiome": "Water-World",
    "habitability": {
      "primary": "Barren",
      "secondary": "Volcanic",
      "hostile": "Water-World"
    },
    "disposition": {
      "aggression": 2,
      "devotion": 10,
      "expansionism": 7,
      "isolationism": 5,
      "mercantilism": 9
    },
    "aggression": 2,
    "devotion": 10,
    "expansionism": 7,
    "isolationism": 5,
    "mercantilism": 9,
    "civilisation": {
      "techBias": "Spiritual",
      "governmentType": "Theocracy",
      "culture": "Dominance"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20mechanical%20face%20portrait%2C%20iridescent%20scales%2C%20flat%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=138174279",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_2a9jyf_mpamwjgp.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_2a9jyf_mpamwjgp.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "hfbxs_mpamyaqe",
    "name": "Kravox Mynok, Tide-Caller",
    "short": "Kravox",
    "epithet": "Tide-Caller",
    "description": "Hydrodynamic lifeforms with pressure-resistant plating and sonar-based neural communication.",
    "biology": "Aquatic",
    "race": "Aquatic",
    "seed": 29268784,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Aquatic alien species. thick rubbery skin like a whale or shark, translucent fins, wet glistening texture, deep-sea monstrous scales, absolutely NO human features. HEAD: Fin-Tipped structure with unique silhouette. EYES: 1 Heat-vision-pits eyes that look completely non-human. SURFACE: Corroded Etchings texture with a #9d00ff primary hue. GARB: Wearing Holographic Shroud. UNIQUE: Features Metallic Spikes. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Fin-Tipped",
    "eyeStyle": "Heat-vision-pits",
    "eyeCount": 1,
    "clothing": "Holographic Shroud",
    "markingPattern": "Corroded Etchings",
    "morphology": "Metallic Spikes",
    "color": "#9d00ff",
    "glyph": "◈",
    "primaryBiome": "Water-World",
    "secondaryBiome": "Sub-Surface Ocean Sphere",
    "hostileBiome": "Arid Desert",
    "habitability": {
      "primary": "Water-World",
      "secondary": "Sub-Surface Ocean Sphere",
      "hostile": "Arid Desert"
    },
    "disposition": {
      "aggression": 5,
      "devotion": 6,
      "expansionism": 6,
      "isolationism": 1,
      "mercantilism": 10
    },
    "aggression": 5,
    "devotion": 6,
    "expansionism": 6,
    "isolationism": 1,
    "mercantilism": 10,
    "civilisation": {
      "techBias": "Biological",
      "governmentType": "Democracy",
      "culture": "Freedom"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20aquatic%20face%20portrait%2C%20corroded%20etchings%2C%20fin-tipped%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=29268784",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_hfbxs_mpamyaqe.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_hfbxs_mpamyaqe.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "vo8vf_mpan0204",
    "name": "Pylen Collective, Slime-King",
    "short": "Pylen",
    "epithet": "Slime-King",
    "description": "Highly adaptive protoplasmic entities capable of rapid cellular reconfiguration.",
    "biology": "Amorphous",
    "race": "Amorphous",
    "seed": 53199339,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Amorphous alien species. viscous translucent slime, shifting protoplasmic mass, lack of symmetry, gelatinous undulating surface, multiple small erratic nuclei. HEAD: Flat structure with unique silhouette. EYES: 1 Diamond eyes that look completely non-human. SURFACE: Runic Carvings texture with a #00ff88 primary hue. GARB: Wearing Tribal leather wraps. UNIQUE: Features Exposed brain lobes. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Flat",
    "eyeStyle": "Diamond",
    "eyeCount": 1,
    "clothing": "Tribal leather wraps",
    "markingPattern": "Runic Carvings",
    "morphology": "Exposed brain lobes",
    "color": "#00ff88",
    "glyph": "⬡",
    "primaryBiome": "Sub-Surface Ocean Sphere",
    "secondaryBiome": "Water-World",
    "hostileBiome": "Barren",
    "habitability": {
      "primary": "Sub-Surface Ocean Sphere",
      "secondary": "Water-World",
      "hostile": "Barren"
    },
    "disposition": {
      "aggression": 3,
      "devotion": 7,
      "expansionism": 7,
      "isolationism": 3,
      "mercantilism": 9
    },
    "aggression": 3,
    "devotion": 7,
    "expansionism": 7,
    "isolationism": 3,
    "mercantilism": 9,
    "civilisation": {
      "techBias": "Biological",
      "governmentType": "Democracy",
      "culture": "Knowledge"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20amorphous%20face%20portrait%2C%20runic%20carvings%2C%20flat%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=53199339",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_vo8vf_mpan0204.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_vo8vf_mpan0204.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "18hymae_mpan1t9o",
    "name": "Fenus Fentor, The Ancient",
    "short": "Fenus",
    "epithet": "The Ancient",
    "description": "Cold-blooded saurians with reinforced dermal plating and acute predatory instincts.",
    "biology": "Reptilian",
    "race": "Reptilian",
    "seed": 2690680406,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Reptilian alien species. thick crocodilian scales, leathery skin, heavy brow ridges, cold-blooded predatory gaze, dinosaur-like textures. HEAD: Snouted structure with unique silhouette. EYES: 4 Milky-White eyes that look completely non-human. SURFACE: Corroded Etchings texture with a #ff8800 primary hue. GARB: Wearing Tattered Nomad Cloak. UNIQUE: Features Multi-layered Crest. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Snouted",
    "eyeStyle": "Milky-White",
    "eyeCount": 4,
    "clothing": "Tattered Nomad Cloak",
    "markingPattern": "Corroded Etchings",
    "morphology": "Multi-layered Crest",
    "color": "#ff8800",
    "glyph": "✴",
    "primaryBiome": "Arid Desert",
    "secondaryBiome": "Volcanic",
    "hostileBiome": "Arctic Tundra",
    "habitability": {
      "primary": "Arid Desert",
      "secondary": "Volcanic",
      "hostile": "Arctic Tundra"
    },
    "disposition": {
      "aggression": 7,
      "devotion": 6,
      "expansionism": 2,
      "isolationism": 9,
      "mercantilism": 5
    },
    "aggression": 7,
    "devotion": 6,
    "expansionism": 2,
    "isolationism": 9,
    "mercantilism": 5,
    "civilisation": {
      "techBias": "Biological",
      "governmentType": "Theocracy",
      "culture": "Dominance"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20reptilian%20face%20portrait%2C%20corroded%20etchings%2C%20snouted%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=2690680406",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_18hymae_mpan1t9o.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_18hymae_mpan1t9o.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "1f6z5vp_mpan4fen",
    "name": "Bochtor, Void-Skitterer",
    "short": "Bochtor",
    "epithet": "Void-Skitterer",
    "description": "Xenooids are chitinous organisms with complex social structures and highly efficient communal processing.",
    "biology": "Insectoid",
    "race": "Insectoid",
    "seed": 3095493253,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Insectoid alien species. hard chitinous exoskeleton, segmented thorax, chitin plating, bristly hairs, compound predatory insect features, no human nose or mouth. HEAD: Elongated structure with unique silhouette. EYES: 6 Diamond eyes that look completely non-human. SURFACE: Iridescent Scales texture with a #ffff00 primary hue. GARB: Wearing Holographic Shroud. UNIQUE: Features Metallic Spikes. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Elongated",
    "eyeStyle": "Diamond",
    "eyeCount": 6,
    "clothing": "Holographic Shroud",
    "markingPattern": "Iridescent Scales",
    "morphology": "Metallic Spikes",
    "color": "#ffff00",
    "glyph": "⊕",
    "primaryBiome": "Lush Forest",
    "secondaryBiome": "Volcanic",
    "hostileBiome": "Arctic Tundra",
    "habitability": {
      "primary": "Lush Forest",
      "secondary": "Volcanic",
      "hostile": "Arctic Tundra"
    },
    "disposition": {
      "aggression": 9,
      "devotion": 1,
      "expansionism": 9,
      "isolationism": 7,
      "mercantilism": 3
    },
    "aggression": 9,
    "devotion": 1,
    "expansionism": 9,
    "isolationism": 7,
    "mercantilism": 3,
    "civilisation": {
      "techBias": "Nomadic",
      "governmentType": "Warlord Council",
      "culture": "Dominance"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20insectoid%20face%20portrait%2C%20iridescent%20scales%2C%20elongated%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=3095493253",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1f6z5vp_mpan4fen.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1f6z5vp_mpan4fen.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "19ec8ze_mpan66op",
    "name": "Vakvox Union, Shift-Walker",
    "short": "Vakvox",
    "epithet": "Shift-Walker",
    "description": "Vaporous energy-based beings that exist within magnetic containment fields.",
    "biology": "Ethereal",
    "race": "Ethereal",
    "seed": 2745064058,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Ethereal alien species. body made of shifting nebulous gas and electrical arcs, held together by a magnetic harness, glowing semi-transparent forms, no solid skin. HEAD: Angular structure with unique silhouette. EYES: 2 Bioluminescent eyes that look completely non-human. SURFACE: Tiger-like banding texture with a #00f2ff primary hue. GARB: Wearing Minimalist Tunic. UNIQUE: Features Ossified plates. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Angular",
    "eyeStyle": "Bioluminescent",
    "eyeCount": 2,
    "clothing": "Minimalist Tunic",
    "markingPattern": "Tiger-like banding",
    "morphology": "Ossified plates",
    "color": "#00f2ff",
    "glyph": "✦",
    "primaryBiome": "Exotic",
    "secondaryBiome": "Barren",
    "hostileBiome": "Lush Forest",
    "habitability": {
      "primary": "Exotic",
      "secondary": "Barren",
      "hostile": "Lush Forest"
    },
    "disposition": {
      "aggression": 1,
      "devotion": 9,
      "expansionism": 8,
      "isolationism": 1,
      "mercantilism": 1
    },
    "aggression": 1,
    "devotion": 9,
    "expansionism": 8,
    "isolationism": 1,
    "mercantilism": 1,
    "civilisation": {
      "techBias": "Spiritual",
      "governmentType": "Theocracy",
      "culture": "Faith"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20ethereal%20face%20portrait%2C%20tiger-like%20banding%2C%20angular%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=2745064058",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_19ec8ze_mpan66op.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_19ec8ze_mpan66op.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "1tnpy7t_mpan7xyk",
    "name": "Gryius Consortium, Coral-Guard",
    "short": "Gryius",
    "epithet": "Coral-Guard",
    "description": "Hydrodynamic lifeforms with pressure-resistant plating and sonar-based neural communication.",
    "biology": "Aquatic",
    "race": "Aquatic",
    "seed": 3970143353,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Aquatic alien species. thick rubbery skin like a whale or shark, translucent fins, wet glistening texture, deep-sea monstrous scales, absolutely NO human features. HEAD: Fin-Tipped structure with unique silhouette. EYES: 6 Multiple-Small eyes that look completely non-human. SURFACE: Mossy patches texture with a #ff0055 primary hue. GARB: Wearing Minimalist Tunic. UNIQUE: Features Crystalline Spines. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Fin-Tipped",
    "eyeStyle": "Multiple-Small",
    "eyeCount": 6,
    "clothing": "Minimalist Tunic",
    "markingPattern": "Mossy patches",
    "morphology": "Crystalline Spines",
    "color": "#ff0055",
    "glyph": "△",
    "primaryBiome": "Water-World",
    "secondaryBiome": "Sub-Surface Ocean Sphere",
    "hostileBiome": "Arid Desert",
    "habitability": {
      "primary": "Water-World",
      "secondary": "Sub-Surface Ocean Sphere",
      "hostile": "Arid Desert"
    },
    "disposition": {
      "aggression": 6,
      "devotion": 3,
      "expansionism": 2,
      "isolationism": 8,
      "mercantilism": 5
    },
    "aggression": 6,
    "devotion": 3,
    "expansionism": 2,
    "isolationism": 8,
    "mercantilism": 5,
    "civilisation": {
      "techBias": "Biological",
      "governmentType": "Theocracy",
      "culture": "Dominance"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20aquatic%20face%20portrait%2C%20mossy%20patches%2C%20fin-tipped%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=3970143353",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1tnpy7t_mpan7xyk.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1tnpy7t_mpan7xyk.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "10v3l34_mpan9p88",
    "name": "Gryia, Slime-King",
    "short": "Gryia",
    "epithet": "Slime-King",
    "description": "Highly adaptive protoplasmic entities capable of rapid cellular reconfiguration.",
    "biology": "Amorphous",
    "race": "Amorphous",
    "seed": 2229017728,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Amorphous alien species. viscous translucent slime, shifting protoplasmic mass, lack of symmetry, gelatinous undulating surface, multiple small erratic nuclei. HEAD: Dome structure with unique silhouette. EYES: 8 Vertical-pupils eyes that look completely non-human. SURFACE: Corroded Etchings texture with a #9d00ff primary hue. GARB: Wearing Minimalist Tunic. UNIQUE: Features Retractable Gills. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Dome",
    "eyeStyle": "Vertical-pupils",
    "eyeCount": 8,
    "clothing": "Minimalist Tunic",
    "markingPattern": "Corroded Etchings",
    "morphology": "Retractable Gills",
    "color": "#9d00ff",
    "glyph": "◈",
    "primaryBiome": "Sub-Surface Ocean Sphere",
    "secondaryBiome": "Water-World",
    "hostileBiome": "Barren",
    "habitability": {
      "primary": "Sub-Surface Ocean Sphere",
      "secondary": "Water-World",
      "hostile": "Barren"
    },
    "disposition": {
      "aggression": 8,
      "devotion": 5,
      "expansionism": 6,
      "isolationism": 4,
      "mercantilism": 9
    },
    "aggression": 8,
    "devotion": 5,
    "expansionism": 6,
    "isolationism": 4,
    "mercantilism": 9,
    "civilisation": {
      "techBias": "Nomadic",
      "governmentType": "Merchant Guild",
      "culture": "Survival"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20amorphous%20face%20portrait%2C%20corroded%20etchings%2C%20dome%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=2229017728",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_10v3l34_mpan9p88.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_10v3l34_mpan9p88.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "v0tz78_mpanbfqs",
    "name": "Vaxtor Unity, Void-Shadow",
    "short": "Vaxtor",
    "epithet": "Void-Shadow",
    "description": "Vaporous energy-based beings that exist within magnetic containment fields.",
    "biology": "Ethereal",
    "race": "Ethereal",
    "seed": 1875850100,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Ethereal alien species. body made of shifting nebulous gas and electrical arcs, held together by a magnetic harness, glowing semi-transparent forms, no solid skin. HEAD: Angular structure with unique silhouette. EYES: 4 Holographic eyes that look completely non-human. SURFACE: Iridescent Scales texture with a #00ff88 primary hue. GARB: Wearing Ornate Silk Robes. UNIQUE: Features Hollow Wing-Spans. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Angular",
    "eyeStyle": "Holographic",
    "eyeCount": 4,
    "clothing": "Ornate Silk Robes",
    "markingPattern": "Iridescent Scales",
    "morphology": "Hollow Wing-Spans",
    "color": "#00ff88",
    "glyph": "⬡",
    "primaryBiome": "Exotic",
    "secondaryBiome": "Barren",
    "hostileBiome": "Lush Forest",
    "habitability": {
      "primary": "Exotic",
      "secondary": "Barren",
      "hostile": "Lush Forest"
    },
    "disposition": {
      "aggression": 6,
      "devotion": 7,
      "expansionism": 3,
      "isolationism": 8,
      "mercantilism": 10
    },
    "aggression": 6,
    "devotion": 7,
    "expansionism": 3,
    "isolationism": 8,
    "mercantilism": 10,
    "civilisation": {
      "techBias": "Spiritual",
      "governmentType": "Democracy",
      "culture": "Knowledge"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20ethereal%20face%20portrait%2C%20iridescent%20scales%2C%20angular%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=1875850100",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_v0tz78_mpanbfqs.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_v0tz78_mpanbfqs.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  },
  {
    "id": "1ggbq99_mpand6zw",
    "name": "Vaxtor Tertor, Tide-Caller",
    "short": "Vaxtor",
    "epithet": "Tide-Caller",
    "description": "Hydrodynamic lifeforms with pressure-resistant plating and sonar-based neural communication.",
    "biology": "Aquatic",
    "race": "Aquatic",
    "seed": 3171662253,
    "visualPrompt": "A stunning cinema-grade macro portrait of a bizarre Aquatic alien species. thick rubbery skin like a whale or shark, translucent fins, wet glistening texture, deep-sea monstrous scales, absolutely NO human features. HEAD: Elephantine structure with unique silhouette. EYES: 5 Milky-White eyes that look completely non-human. SURFACE: Runic Carvings texture with a #ff8800 primary hue. GARB: Wearing Tattered Nomad Cloak. UNIQUE: Features Floating Shards. STYLE: High-detail cinematic Sci-Fi, Greg Rutkowski style, photorealistic textures, dramatic rim lighting, depth of field, 4k, intricately detailed surface anatomy, BREAK THE HUMAN SILHOUETTE, Star Wars creature design.",
    "headShape": "Elephantine",
    "eyeStyle": "Milky-White",
    "eyeCount": 5,
    "clothing": "Tattered Nomad Cloak",
    "markingPattern": "Runic Carvings",
    "morphology": "Floating Shards",
    "color": "#ff8800",
    "glyph": "✴",
    "primaryBiome": "Water-World",
    "secondaryBiome": "Sub-Surface Ocean Sphere",
    "hostileBiome": "Arid Desert",
    "habitability": {
      "primary": "Water-World",
      "secondary": "Sub-Surface Ocean Sphere",
      "hostile": "Arid Desert"
    },
    "disposition": {
      "aggression": 1,
      "devotion": 10,
      "expansionism": 6,
      "isolationism": 4,
      "mercantilism": 1
    },
    "aggression": 1,
    "devotion": 10,
    "expansionism": 6,
    "isolationism": 4,
    "mercantilism": 1,
    "civilisation": {
      "techBias": "Mechanical",
      "governmentType": "Warlord Council",
      "culture": "Survival"
    },
    "portraitUrl": "https://image.pollinations.ai/prompt/alien%20aquatic%20face%20portrait%2C%20runic%20carvings%2C%20elephantine%20head%2C%20sci-fi%20cinematic%20lighting%2C%20dark%20background%2C%20detailed?width=512&height=512&nologo=true&seed=3171662253",
    "portraitGitHubUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1ggbq99_mpand6zw.jpg",
    "portraitDriveUrl": "https://raw.githubusercontent.com/mtgedney/aether/main/portraits/portrait_1ggbq99_mpand6zw.jpg",
    "generatedAt": "2026-05-18T03:33:19.405Z",
    "botVersion": "1.0"
  }
];